### ISSUE TITLE
Packges for Fedora 36?

### ISSUE THREAD

**Issue by devmotion** [lawmurray/Birch#17]
Hej :slightly_smiling_face: 

I just wanted to install Birch on my new computer and noticed that there are no pre-built packages available for Fedora 36. Of course, I could just compile Birch but that takes time and is less convenient than the distribution packages when I don't intend to work on Birch itself. Maybe it would be helpful also for other users to update the supported distros in the OBS and build the latest release for newer versions of Fedora, openSUSE, etc. as wel?

**Comment by lawmurray** [comment]
Now available on [OBS](https://software.opensuse.org//download.html?project=home%3Alawmurray%3Abirch&package=birch) @devmotion.

Background to this is that on last attempt, Fedora 36 builds were failing on OBS. That no longer seems to be the case.

**Comment by devmotion** [comment]
Great, thank you! It seems to work so far :slightly_smiling_face:
