### ISSUE TITLE
Error with cloning

### ISSUE THREAD

**Issue by aakhmetz** [lawmurray/Birch#24]
Not sure if it is important, but if I run:
```
git clone -b stable https://github.com/lawmurray/Birch.git
```
I would get
```
fatal: Remote branch stable not found in upstream origin
```

**Comment by devmotion** [comment]
This repository does not have a `stable` branch. You can clone the default branch (`master`) by simply running
```shell
git clone https://github.com/lawmurray/Birch.git
```

**Comment by aakhmetz** [comment]
Thank you - I did the same. I was just wondering if README.md could be corrected

**Comment by lawmurray** [comment]
Thanks for raising this @aakhmetz, and thanks @devmotion for the quick fix to the readme!
